#!/usr/bin/python3

from tkinter import *
class Checkbar(Frame):
   def __init__(self, parent=None, picks=[], side=LEFT, anchor=W):
      Frame.__init__(self, parent)
      self.vars = []
      for pick in picks:
         var = IntVar()
         chk = Checkbutton(self, text=pick, variable=var)
         chk.pack(side=side, anchor=anchor, expand=YES)
         self.vars.append(var)
   def state(self):
      return map((lambda var: var.get()), self.vars)

# tkinter import wird benötigt, damit die Checkbox dargestellt werden kann, dies geschieht mit einer Variable und unter der Variable wird das Design dargestellt.

if __name__ == '__main__':
   root = Tk()
   lng = Checkbar(root, ['Großbuchstaben', 'Kleinbuchstaben', 'Zahlen', 'Zeichen'])
   lng.pack(side=TOP,  fill=X)
   lng.config(relief=GROOVE, bd=2)

   # Hier wird eingetragen, was in der Checkbox angezeigt werden soll.

   def allstates(): 
      print(list(lng.state()), list(tgl.state()))
   Button(root, text='generate', command=root.quit).pack(side=RIGHT)
   
root.mainloop()

# Leider funktioniert die Checkbox nicht ganz, wie sie soll. Mit den Button "generate" wird man zur nächsten funktion weiter geleitet, bei der gefragt wird, wie lange das Passwort werden soll. Es werden alle Checkboxen beachtet, auch wenn man nich alle auswählt.


import secrets

pw = ""
Großbuchstaben ="QWERTZUIOPASDFGHJKLYXCVBNM"
Kleinbuchstaben ="qwertzuiopasdfghjklyxcvbnm"
Zeichen =",.-^^&%)(/?=>:;"
Zahlen ="1230456978"

# Definition aus Variablen aus dem das Passwort zufällig  durch die untere Funktion dargestellt wird. Durch das import secrets wird das Passwort zufällig erstellt.

laenge = int(input("Bitte Passwortlänge eingeben: "))

for _ in range(laenge):
    pw = pw+secrets.choice(Zeichen+Großbuchstaben+Kleinbuchstaben+Zahlen)
    
print(pw)
