#!/usr/bin/python3

from tkinter import *
class Checkbar(Frame):
   def __init__(self, parent=None, picks=[], side=LEFT, anchor=W):
      Frame.__init__(self, parent)
      self.vars = []
      for pick in picks:
         var = IntVar()
         chk = Checkbutton(self, text=pick, variable=var)
         chk.pack(side=side, anchor=anchor, expand=YES)
         self.vars.append(var)
   def state(self):
      return map((lambda var: var.get()), self.vars)
if __name__ == '__main__':
   root = Tk()
   lng = Checkbar(root, ['Großbuchstaben', 'Kleinbuchstaben', 'Zahlen', 'Zeichen'])
   lng.pack(side=TOP,  fill=X)
   lng.config(relief=GROOVE, bd=2)

   def allstates(): 
      print(list(lng.state()), list(tgl.state()))
   Button(root, text='generate', command=root.quit).pack(side=RIGHT)
   
root.mainloop()


import secrets

pw = ""
Großbuchstaben ="QWERTZUIOPASDFGHJKLYXCVBNM"
Kleinbuchstaben ="qwertzuiopasdfghjklyxcvbnm"
Zeichen =",.-^^&%)(/?=>:;"
Zahlen ="1230456978"

laenge = int(input("Bitte Passwortlänge eingeben: "))

for _ in range(laenge):
    pw = pw+secrets.choice(Zeichen+Großbuchstaben+Kleinbuchstaben+Zahlen)
    
print(pw)
